[package]
name = "omni-lance"
version.workspace = true
edition.workspace = true
description = "LanceDB RecordBatch utilities"
authors = ["Omni-Dev-Fusion Team"]
license = "Apache-2.0"
publish = false

[dependencies]
lance = "2.0"

[lints]
workspace = true
