branch_whitelist = ["main", "release/**"]
ignore_merge_commits = true
post_bump_hooks = ["branch=\"$(echo \"release/{{version}}\" | sed 's/\\.[^.]*$//')\"\ngit push --set-upstream origin \"$branch\"\ngit push origin v{{version}}\n\ngit switch main\ngit merge \"$branch\" --no-commit --no-ff\necho {{version+minor-dev}} > ./VERSION\ngit add VERSION\ngit commit -m \"chore: sync with release\"\ngit push origin main\n", "cog -q changelog --at v{{version}}"]
pre_bump_hooks = ["echo {{version}} > ./VERSION", "branch=\"$(echo \"release/{{version}}\" | sed 's/\\.[^.]*$//')\"\nif [ `git rev-parse --verify $branch 2>/dev/null` ]\nthen\n  git switch -m \"$branch\" || exit 1\n  git merge main\nelse\n  git switch -c \"$branch\" || exit 1\nfi\n"]
tag_prefix = "v"

[changelog]
owner = "tao3k"
path = "CHANGELOG.md"
remote = "github.com"
repository = "omni-devenv-fusion"
template = "remote"
[[changelog.authors]]
signature = "Guangtao"
username = "gtrunsec"

[scope]
options = [
    "nix",
    "mcp",
    "router",
    "docs",
    "cli",
    "deps",
    "ci",
]
