# Zettelkasten configuration for Omni Dev Fusion
# Monorepo: entire project is the notebook

[note]
filename = "{{date}}-{{slug}}"

[note.template]
header = """
# {{title}}

"""
extension = "md"
extra-fields = []

[search]
use-ripgrep = true
